os:
  - osx
  - linux
language:       python
sudo:           false
python:
    - '3.6'
addons:
  apt:
    packages:
        - pandoc
        - libffi-dev
        - libffi6
install:
    - pushd . && cp requirements.txt ~/ && cd ~/
    - travis_retry pip install -r requirements.txt -q
    - rm requirements.txt && popd
script:
    - python setup.py build_ext --inplace
    - coverage run --source unvcf -m pytest
    - python setup.py install && pip uninstall unvcf --yes
    - python setup.py sdist
    - pip install dist/$(ls dist | grep -i -E '\.(gz)$' | head -1)
    - pip uninstall unvcf --yes
after_success:
    - codecov
notifications:
  email:
    recipients:
    - danilo.horta@gmail.com
    on_success: never
    on_failure: always
